apiVersion: v1
kind: Namespace
metadata:
  name: production
  labels:
    # Reject any pod that does not meet the "restricted" Pod Security Standard.
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
